### ISSUE TITLE
axios to be added as a dependency

### ISSUE THREAD

**Issue by Aigarsss** [aviemet/useInertiaForm#13]
I think Axios should be added as an dependency on the package, because the package doesnt work without axios installed.

**Comment by aviemet** [comment]
I didn't include it because axios is a dependency of inertia, which is listed as a dependency. I'm not sure if it's necessary to list it, but if so we can certainly add it.

**Comment by Aigarsss** [comment]
Yeahm sorry, looks like it was some sort of a one time glitch on my end. Should be fine with the dependency included with Inertia.
