### ISSUE TITLE
Form not updating after submit

### ISSUE THREAD

**Issue by domhaas** [aviemet/useInertiaForm#15]
Hi there,

I got a strange behavior after submitting the form.

The form is correctly submitted to laravel and the data-prop is also correctly updated. But "isDirty" is still on "true". And also "recentlySuccessful" is not working correctly: it goes to "true" but after the timeout stays on "true".

Am I doing something wrong here? The normal Inertia-Formhandling works without any issues.

Pseudo-Code:
```
export default function Show({ data }: PageProps<{ data: BaseObject }>) {
    return (
        <Form data={data} to={`/users/${data.id}`} method="patch">
            ...

            <Flowbite_TextInput
                id={id || inputId}
                name={inputName}
                onChange={e => {
                    if (onChange) onChange(e.target.value, form);
                    setValue(e.target.value);
                }}
                value={value}
                required={required}
                color={error ? "failure" : undefined}
                helperText={<>{error}</>}
                {...props}
            />

            ...

            <SubmitButton
                component={Button}
                ref={ref}
                disabled={disabled || !isDirty}
                {...props}>
                {children}
            </SubmitButton>

            ...

        </Form>;
    );
}
```

Thank you in advance.

**Comment by aviemet** [comment]
Apologies for the late response. I have a sneaking suspicion that this may have been the result of how I was memoizing these methods. I removed the memoization due to some other issues, so that may have fixed the one you're experiencing. If not, I'd love to help troubleshoot further.

**Comment by domhaas** [comment]
> Apologies for the late response. I have a sneaking suspicion that this may have been the result of how I was memoizing these methods. I removed the memoization due to some other issues, so that may have fixed the one you're experiencing. If not, I'd love to help troubleshoot further.

Thanks. Currently not using your lib any more, but much appreciated for coming back to my issue.
Cheers.
