### ISSUE TITLE
Bug when using a form with only one key inside

### ISSUE THREAD

**Issue by girardinsamuel** [aviemet/useInertiaForm#28]
Hi,

Thanks for this package which implements exaclty what's missing from Inertia 🙏  !

I am using it on my side and it works well with nested data. However for the very simple (edge) case with only one key in the form, the package is assuming (from this line below) that there is nested data :
https://github.com/aviemet/useInertiaForm/blob/7354d248af006c0ab2b110221fbbc95a4c48a398/src/useInertiaForm.ts#L107
and when server return errors, form errors are set nested even if it's not...

```tsx
// With this form :
const form useInertiaForm({
    offering: ""
})

// when server returns {"offering": "error message"}
// form helper is loading errors as
{"offering.offering": "error message"}
```
Do you think we can solve this ? For now I am using a workaround to look for errors as `form.errors.offering.offering` or `form.getError("offering.offering")` but that's not very convenient.

Thanks !

**Comment by girardinsamuel** [comment]
Hi ! Did you have time to look into this ? What do you think ? 
Thanks !

**Comment by aviemet** [comment]
Guess I need to check in on this repo more often, sorry I'm seeing this so long after you posted.

You're absolutely right about that line, it would definitely nest a flat data object containing only one element in a root key. I believe I have a simple enough fix to check if the value is a nested object, but I want to write some tests to be sure. I'm hoping I can get to it after the holiday.

**Comment by aviemet** [comment]
Hi @girardinsamuel , I believe the latest release fixes this issue. I'm going to close it, so please feel free to reopen it if not.
