### ISSUE TITLE
bundle-size

### ISSUE THREAD

**Issue by domhaas** [aviemet/useInertiaForm#29]
Hey there,

I got some issue while deploying an application. It seems like lodash as dependency of useInertiaForm is blowing the bundle-size to the limit:

![image](https://github.com/user-attachments/assets/7f0787e1-203f-4147-b6db-d8fc51999c80)

Issue on my side, or are there some things we could do to optimize it here? tree-shakin might be a point.

Thanks!

Cheers,
Dom

**Comment by aviemet** [comment]
I'll be honest, I'm not very familiar or comfortable with publishing packages or optimizing bundle sizes. If you have any suggestions I'd love to get them, I'm currently trying some things out on the bundle branch. So far I've tried moving all non dev-dependencies into peerDependencies, but when building, the bundle size doesn't change much at all for me.

I'm going to keep trying to optimize, and I'll make another release in a few days once I've tried some things out. Do let me know if you have any tips though.

**Comment by domhaas** [comment]
> I'll be honest, I'm not very familiar or comfortable with publishing packages or optimizing bundle sizes. If you have any suggestions I'd love to get them, I'm currently trying some things out on the bundle branch. So far I've tried moving all non dev-dependencies into peerDependencies, but when building, the bundle size doesn't change much at all for me.
> 
> I'm going to keep trying to optimize, and I'll make another release in a few days once I've tried some things out. Do let me know if you have any tips though.

Thanks @aviemet for your reply,

I'm not really a professional with build processes either - but I think I already have a clue.
I'll get back to you in a few days with a change request.
